### ISSUE TITLE
Define/Implement ResultOption

### ISSUE THREAD

**Issue by SundeMarius** [SundeMarius/arduino_menu_system#8] opened 2020-07-07 15:36 UTC
An option which is a response to the user after some option is selected
Ex: "Turn lights on (Y/N)"
       "Y"
       "Lights are on!"  <--- ResultOption!

**Comment by SundeMarius** [comment] 2020-07-07 15:39
Maybe it should have callback (some return value) to send the action to the object responsible to turn lights on

**Comment by ANicholasson** [comment] 2020-07-08 07:57
This issue might be a duplicate of #7. A solution for the callback issue is to create a new parent (abstract) class that forces callback on its children (inheritance). Or maybe we should add that in MenuOption as probably most options require some sort of callback? Could also add it as an optional choice in MenuOption.

**Comment by SundeMarius** [comment] 2020-07-08 18:23
Yes, I see now that this is indeed a duplicate. Depending on the implementation, we may want to have a callback on every option and use that callback to switch the state of the menu i.e go to the next option in the tree.
However, the way to implement the action specific to the selected option is still an exercise to solve, but I think it is natural to make it part of the selected option. Since all options are a MenuOption, I would naively put that action part of MenuOption.

**Closed as completed** 2021-01-16 16:03 UTC
